services:
  app:
    image: flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: flask_mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads

  mysql:
    container_name: flask_mysql
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    container_name: test_app
    image: test:latest
    ports:
      - "5001:5000"

volumes:
  mysql-data:
    driver: local

