flask:
  image: noa10203040/flask_app:latest
  replicas: 1
  containerPort: 5000
  servicePort: 80    
  useS3: true           
  aws:
    accessKeyIdSecret: aws-credentials  
    secretAccessKeySecret: aws-credentials
    region: us-east-1
