mysql:
  image: mysql:latest
  pvcName: mysql-pvc1
  useExistingPVC: true
  rootPassword: password
  database: flask
  user: flask
  password: password
  storage: 1Gi

flask:
  image: noa10203040/flask_app:latest
  replicas: 1
  containerPort: 5000
  servicePort: 80    
  pvcName: uploads-pvc
  useExistingPVC: true
  storage: 1Gi
  aws:
    accessKeyIdSecret: aws-credentials
    secretAccessKeySecret: aws-credentials
    region: us-east-1

