namespace: prod

serviceAccount:
  create: true
  name: flask-app-sa
  annotations:
    azure.workload.identity/client-id: "YOUR_AZURE_IDENTITY_CLIENT_ID"

flask:
  image: noa10203040/flask_app:90476060
  replicas: 1
  containerPort: 5000
  servicePort: 80
  hostname: my-favorite-second-hand-shop.com
  secretKey: prod_secret_key
  podLabels:
    azure.workload.identity/use: "true"

db:
  host: "flask-db.postgres.database.azure.com" 
  name: "second_hand_shop"
  user: "psqladmin"
  port: 5432

azure:
  keyvaultUrl: "https://your-vault-name.vault.azure.net/"
  storageAccountName: "yourstorageaccountname"
  containerName: "clothes-images"