services:
  flask_app:
    container_name: flask_app
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: noa10203040/flask_app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    container_name: test
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password
    command: ["/bin/sh", "-c", "/app/wait-for-mysql.sh && pytest app_test.py --maxfail=1 --disable-warnings -q"]

volumes:
  mysql-data:

