version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: noa10203040/flask_app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 10

  test:
    container_name: test
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: ["/bin/sh", "-c", "/app/wait-for-mysql.sh && pytest app_test.py --maxfail=1 --disable-warnings -q"]

volumes:
  mysql-data:
