services:
 flask_app:
   container_name: flask_app
   build:
     context: ../backend
     dockerfile: Dockerfile
   image: noa10203040/flask_app:latest
   ports:
     - "5000:5000"
   volumes:
     - ../backend:/app/backend
     - ../backend/frontend:/app/backend/frontend
     - flask-uploads-volume:/app/backend/frontend/uploads
   environment:
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - AWS_REGION=us-east-1
   env_file:
     - ../database/pass_env1
   depends_on:
     mysql:
       condition: service_healthy


 mysql:
   container_name: mysql
   image: mysql:latest
   env_file:
     - ../database/cred.env
   volumes:
     - mysql-volume:/var/lib/mysql
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5


 test:
   container_name: test_app
   image: test:latest
   build:
     context: ../backend
     dockerfile: Dockerfile
   depends_on:
     - flask_app
     - mysql
   environment:
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - AWS_REGION=us-east-1
   env_file:
     - ../database/pass_env1
   command: ["pytest", "/app/backend/app_test.py"]
   volumes:
     - ../backend:/app/backend
     - ../backend/frontend:/app/backend/frontend
     - flask-uploads-volume:/app/backend/frontend/uploads
volumes:
 flask-uploads-volume:
   external: true
 mysql-volume:
   external: true



