
services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    image: noa10203040/flask_app:latest
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password  
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  # root password
      MYSQL_DATABASE: flask         # DB name
      MYSQL_USER: flask             # user
      MYSQL_PASSWORD: password      # user password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    container_name: test_app
    image: noa10203040/test:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - flask_app
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password
    volumes:
      - .:/app
    command: ["pytest", "app_test.py"]

volumes:
  mysql-data:

