apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'https://github.com/noaeisnkut/second_clothes_project.git' 
    targetRevision: main   
    path: "helm-charts/myproject" 
    helm:
      valueFiles:
        - values-prod.yaml 
  destination:
  server: 'https://kubernetes.default.svc'
  namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
