apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: stage
  source:
    repoURL: 'https://github.com/noaeisnkut/second_clothes_project.git'
    targetRevision: s3
    path: "helm-chart"
    helm:
      valueFiles:
        - helm-chart/values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
