apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: {{ .Values.namespace }}
  labels:
    app: flask
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: flask-app
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.containerPort }}
          env:
            - name: DB_USER
              value: {{ .Values.db.user | default "psqladmin" | quote }}
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | default "second_hand_shop" | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | default "5432" | quote }}
            - name: AZURE_KEYVAULT_URL
              value: {{ .Values.azure.keyvaultUrl | quote }}
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: {{ .Values.azure.storageAccountName | quote }}
            - name: AZURE_STORAGE_CONTAINER
              value: {{ .Values.azure.containerName | default "clothes-images" | quote }}
            - name: SECRET_KEY
              value: {{ .Values.flask.secretKey | quote }}