apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.flask.pvcName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.flask.storage }}
  storageClassName: standard
