# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "second-clothes-project-terraform-state-4321"
    dynamodb_table = "second-clothes-project-tf-lock"
    encrypt        = true
    key            = "live/prod/vpc/terraform.tfstate"
    region         = "us-east-1"
  }
}
