name: test & deploy docker

on:
  push:
    branches:
      - main

jobs:
  build-test-run-second-hand-clothes-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & start containers
        run: docker compose up -d --build

      - name: Check test success
        run: docker compose run --rm test

      - name: Echo success
        if: success()
        run: echo "Amazing! Everything works, test passed!"

      - name: Echo failure
        if: failure()
        run: echo "Something went wrong..."

      - name: Take containers down
        run: docker compose down -v

          
      
        
      


         
